version: 2.1

jobs:  # which job to execute pre-defined command 
  build:
    working_directory: ~/hello-world
    docker:      
      - image: circleci/node:10.16.0              
    steps: # steps which you want to run
      - checkout  # checkout for ur repo
      - run:
        name: chk if i m heare
        command: |
          echo "yes i am"

      - run: echo " hi sandeep "
      - run: |
          ls
          npm i
          node index.js         
        background: true    


